channels:
- defaults
- pytorch
- pypi
dependencies:
- python=3.8
- jupyter
- jupyterlab
# Plotting utilities
- dash # Dash by Plotly to create dashboard
- plotly
- matplotlib
- seaborn
# Dataframe
- pandas
- numpy
- geopandas # for conveniently working with geoJSON files.
- descartes # for ploting with geopandas.
- shapely # For working with neighborhood boundary polygons.
# ML
- scikit-learn
- pip:
  - APScheduler # for scheduling Tweets gather.
  - jsonmerge # used to merge json files since results from API can have multiple pages.
  - dash-ui # add on package to implement grid layout for dash
  - tweepy # API to gather tweets.
  - tensorflow # also support GPU if compatible NVIDIA GPU exists.
name: improve_neighborhood_safety