channels:
- defaults
- pytorch
- pypi
dependencies:
- python=3.8
- jupyter
- jupyterlab
- dash # Dash by Plotly to create dashboard
- plotly
- matplotlib
- seaborn
- pandas
- numpy
- scikit-learn
- shapely # For working with neighborhood boundary polygons.
- pip:
  - tweepy # API to gather tweets.
  - tensorflow # also support GPU if compatible NVIDIA GPU exists.
name: improve_neighborhood_safety